version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bookera_user
      POSTGRES_PASSWORD: bookera_password
      POSTGRES_DB: bookera_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"