version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: booksy_user
      POSTGRES_PASSWORD: booksy_password
      POSTGRES_DB: booksy_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"